sensors:
  - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
    point_cloud_topic: /scan_matched_points2
    max_range: 4.0
    point_subsample: 20
    padding_offset: 0.0
    padding_scale: 1.0
    filtered_cloud_topic: filtered_cloud
