# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  arm_pitch_joint_1:
    has_velocity_limits: true
    max_velocity: 3.14159265
    has_acceleration_limits: false
    max_acceleration: 0
  arm_pitch_joint_2:
    has_velocity_limits: true
    max_velocity: 4.81710873
    has_acceleration_limits: false
    max_acceleration: 0
  arm_pitch_joint_3:
    has_velocity_limits: true
    max_velocity: 4.81710873
    has_acceleration_limits: false
    max_acceleration: 0
  arm_roll_joint:
    has_velocity_limits: true
    max_velocity: 4.81710873
    has_acceleration_limits: false
    max_acceleration: 0
  arm_yaw_joint:
    has_velocity_limits: true
    max_velocity: 4.81710873
    has_acceleration_limits: false
    max_acceleration: 0
  gripper_finger_joint_1:
    has_velocity_limits: true
    max_velocity: 4.81710873
    has_acceleration_limits: false
    max_acceleration: 0
  gripper_finger_joint_2:
    has_velocity_limits: true
    max_velocity: 4.81710873
    has_acceleration_limits: false
    max_acceleration: 0
  gripper_servo_joint:
    has_velocity_limits: true
    max_velocity: 4.81710873
    has_acceleration_limits: false
    max_acceleration: 0
  sensor_head_pitch_joint:
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0
  sensor_head_yaw_joint:
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0